    </div>
    <?php echo Phalcon\Tag::javascriptInclude("https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js", false); ?>
    <script>window.jQuery||document.write('<script src="../assets/js/vendor/jquery.min.js"><\/script>');</script>
    <?php echo Phalcon\Tag::javascriptInclude('assets/js/vendor/bootstrap.min.js'); ?>
    <?php echo Phalcon\Tag::javascriptInclude('assets/js/vendor/docs.min.js'); ?>
    <?php echo Phalcon\Tag::javascriptInclude('assets/js/vendor/ie10-viewport-bug-workaround.js'); ?>
    <?php echo Phalcon\Tag::javascriptInclude('assets/js/forex.js?ts='. time()); ?>
</body>
</html>
