    </div>
    <?php echo Phalcon\Tag::javascriptInclude('https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js', false) ;?>
    <script>window.jQuery||document.write('<script src="../assets/js/vendor/jquery.min.js"><\/script>');</script>
    <?php echo Phalcon\Tag::javascriptInclude('assets/js/vendor/bootstrap.min.js') ;?>
    <?php echo Phalcon\Tag::javascriptInclude('assets/js/vendor/bootstrap.min.js') ;?>
    <?php echo Phalcon\Tag::javascriptInclude('assets/js/vendor/docs.min.js') ;?>
    <?php echo Phalcon\Tag::javascriptInclude('assets/js/vendor/ie10-viewport-bug-workaround.js') ;?>
</body>
</html>
