<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv=X-UA-Compatible content="IE=edge">
    <meta name=viewport content="width=device-width,initial-scale=1">

    <title>Forex Simulator</title>

    <?php echo Phalcon\Tag::stylesheetLink('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css', false) ;?>
    <?php echo Phalcon\Tag::stylesheetLink('https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css', false) ;?>
    <?php echo Phalcon\Tag::stylesheetLink('assets/css/forex.css') ;?>
</head>
<body>
    <div id="container">
