<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Forex Simulator</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <?php echo $this->tag->stylesheetLink("css/style_home.css") ;?>
</head>
<body>
    <div id="container">
